server.port 9091
server.error.include-message=always
spring.datasource.url=jdbc:mysql://localhost/users?serverTimezone=UTC
spring.datasource.username=adm
spring.datasource.password=adm
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#spring.datasource.username=utilisateurs
#spring.datasource.password=utilisateurs
jwt.secret=root
